### ISSUE TITLE
[Enhancement] Display inheritance in the generated doc of class

### ISSUE THREAD

**Issue by hcoohb** [daizutabi/mkapi#10]
Another interesting improvement could be to be able to display the parent class if the class is a subclass. i.e, just listing the parent classes after the list of parameters.

For example, the following class:
```python
class SubClass(MixinExt, Mixin2):
    def __init__(self, string_a: str):
        pass

```
Would result in a documentation like so:
![mkapi-inheritance](https://pictshare.net/ndgz7d.jpg)

Not sure what you think about that, but I would find it very useful for my usecase.

Thanks and regards

**Comment by daizutabi** [comment]
This feature was added in Version 0.7.7.

<img width="470" alt="img2" src="https://user-images.githubusercontent.com/17495937/84214365-21943e80-aafe-11ea-91d9-bc8d6bf173aa.png">

Because a class signature may be very long with many arguments, inheritance is displayed in a independent line below of the signature. If you use [Page Mode](https://mkapi.daizutabi.net/usage/page/), hyperlink to superclass is automatically created. See [an example here](https://mkapi.daizutabi.net/api/mkapi.core.node/)

**Comment by hcoohb** [comment]
Thanks, that is awesome!

Just one comment:
Would that be possible for this <p> to have a special class so that we can theme is with css?

**Comment by daizutabi** [comment]
Good suggestion. I'll try this.

**Comment by daizutabi** [comment]
Now, "Bases" is a section like "Parameters" and rendered to structured HTML. You can customize the view with css.

<img width="391" alt="img3" src="https://user-images.githubusercontent.com/17495937/84262542-c479a680-ab58-11ea-8de7-75ad375cff3f.png">

**Comment by hcoohb** [comment]
Works great.
Thanks a lot!
